### PR TITLE
Feature/multicast kmp

### PR DESCRIPTION
**Pull request by aclassen**
Any help rewriting tests to kotlin 1.6 is welcome

### CODE REVIEW

**Comment by digitalbuddha** [comment]
This might help https://medium.com/androiddevelopers/migrating-to-the-new-coroutines-1-6-test-apis-b99f7fc47774

**Comment by lukisk** [comment]
@aclassen i can help you with tests, just tell me which module.
btw. we use multiplatform version of store in production :)

**Comment by aclassen** [comment]
@lukisk Many thanks , if you can do the port of multicast tests to coroutines 1.6 then i would take care of filesystem.

**Comment by lukisk** [comment]
@aclassen Yes, i can.

**Comment by digitalbuddha** [comment]
Hey hey, I think we can get away with no multicaster in new store design https://github.com/MobileNativeFoundation/Store/pull/443

**Comment by digitalbuddha** [comment]
I'm going to merge this and then work on tests in some follow up - my thinking is that this passes all checks and is not an active released branch. I'll like to take a stab at it

**Pull request merged**
