### PR TITLE
Add aclassen as co-author of KMP translation

### PR DESCRIPTION
**Pull request by matt-ramotar**
Please see our contributing guidelines (contributing.md) primarily make sure to sign our cla as we cannot accept code externally without a signed cla

https://opensource.dropbox.com/cla/

### CODE REVIEW

**Comment by aclassen** [comment]
Thank you so much 👍

**Comment by aclassen** [comment]
Is there any action needed from my side ?

**Comment by digitalbuddha** [comment]
nope. I'm going to give this another try as the history looked weird

**Comment by digitalbuddha** [comment]
@aclassen I forced push the rewrite to origin/main, does that look right to you?

**Comment by aclassen** [comment]
@digitalbuddha looks fine to me 👍

**Pull request closed without merging**
