### PR TITLE
Support custom error types

### PR DESCRIPTION
**Pull request by matt-ramotar**
> Hello :spock-hand: ! Does someone have any guidance/sample project on how to handle network/http errors with Store? Currently the network layer in our Android app takes care of catching exceptions, parsing error payloads and returning a custom monad class like Result<NetworkError, T>> . Looking at StoreReadResponse it seems that using Throwable or String is the only way to go. Thanks for your answers!

https://kotlinlang.slack.com/archives/C06007Z01HU/p1699457424194509

### CODE REVIEW

**Comment by matt-ramotar** [comment]
@digitalbuddha We would need to fix tests obviously but I wanted to get something up first for discussion. Adding a generic to `StoreReadResponse` and `FetcherResult` would introduce breaking changes I know we don't want. Thoughts?

**Comment by borsini** [comment]
@matt-ramotar thanks for bringing up implementation ideas so quickly. Would it be possible for the `Custom` error to accept any type instead of only `Throwable`? As an example, our network layer uses a sealed interface with no Throwable inheritance. Something like this

```
sealed interface NetworkError { 
    data class StatusCodeError(val statusCode: Int, val error: CustomApiError?) : NetworkError()
    data class UnknownError(val throwable: Throwable) : NetworkError()
    data object NetworkUnavailableError : NetworkError()
}
```

**Comment by matt-ramotar** [comment]
@borsini Seems fine to me 👍🏽

**Review by yigit — APPROVED** [review]
lgtm but we should add a test ideally :)

**Comment by borsini** [comment]
Hello @matt-ramotar, I checked how this PR was doing and came up with an idea. I created this [little draft PR](https://github.com/MobileNativeFoundation/Store/pull/593) to illustrate my thinking. What if, instead of having a sealed hierarchy, Store use only one generic `Error` type.

Let me know what you think 😄

**Comment by matt-ramotar** [comment]
Sorry to be slow @borsini, will try to get this merged by end of week

**Comment by borsini** [comment]
No worries @matt-ramotar this is open source 🙂

**Pull request merged**
