### PR TITLE
Feature/filesystem kmp

### PR DESCRIPTION
**Pull request by aclassen**
Any support rewriting tests is highly appreciated

### CODE REVIEW

**Comment by digitalbuddha** [comment]
I'm ok merging this before tests are backfilled. We won't be doing a release until full conversion is complete and can add tests post merge.

**Comment by aclassen** [comment]
I'm still working on rewriting the tests, sorry for that. We can merge and i create a separate pr for tests as soon im done.

**Comment by digitalbuddha** [comment]
No worries. I just wanted to make sure you aren't waiting on me. No rush from my end

**Comment by matt-ramotar** [comment]
Hey @aclassen Just put up #506 if you want to take a look

**Pull request closed without merging**
